# Ejercicio 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [98]:
# Imports
import numpy as np
import math
from scipy import stats

In [99]:
def ejercicio1(array):
    """
     Función que muestra un resumen estadístico del array enviado como argumento.

     Argumentos:
     arrat -- array de numpy.
     """
    if array.ndim == 1:
        print('Promedio: ' + str(np.mean(array)))
        print('Media: ' + str(np.median(array)))
        print('Moda: ' + str(stats.mode(array)[0][0]))
        print('Varianza: ' + str(np.var(array)))
        print('Desviación Estándar: ' + str(round(np.std(array), 3)))
    else:
        print('El array debe tener 1 dimension')

### Ejemplo de llamada con array de 1 dimension, debe mostrar el resumen

In [100]:
ejercicio1(np.array([1, 2, 3, 4, 5]))

Promedio: 3.0
Media: 3.0
Moda: 1
Varianza: 2.0
Desviacion Standard: 1.414


### Ejemplo de llamada con array de mas de 1 dimension, debe mostrar mensaje de error

In [101]:
ejercicio1(np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]))

El array debe tener 1 dimension


----------------------------------------------------------------------------

# Ejercicio 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [102]:
def ejercicio2(n):
    """
     Función que crea una matriz cuadrada del tamaño dado como parametro.

     Argumentos:
     n -- tamaño de la matriz.
     """
    return random.randint(100, size=(n, n))


In [103]:
print(ejercicio2(3))

[[19 89 93]
 [63 87 63]
 [60 59 33]]


----------------------------------------------------------------------------------------------------

# Ejercicio 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [104]:
def ejercicio3(tabla):
    """
     Función que crea una matriz imprime el total por filas y columnas.

     Argumentos:
     tabla.
     """
    print('Total por filas:' + str(np.sum(tabla, axis = 1)))
    print('Total por comlumnas:' + str(np.sum(tabla, axis = 0)))

In [105]:
ejercicio3(np.array([ [1, 7], [3, 4] ]))

Total por filas:[8 7]
Total por comlumnas:[ 4 11]


----------------------------------------------------------------------------------------------------------

# Ejercicio 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [106]:
def ejercicio4(arrayA, arrayB):
    """
     Función que devuelve el coeficiente de correlación
     
     El coeficiente determina la dependencia lineal entre dos variables. El valor del coeficiente varia de -1 a +1, donde +1 
     determina una relación lineal positiva, y -1 una relacion lineal negativa. Si es cero indica que la relación entre 
     las variables no es linea.
     
    
     Argumentos:
     arrayA - array A
     arrayB - array B
     """
    
    # Calculo de media
    muA = sum(arrayA) / len(arrayA)
    muB = sum(arrayB) / len(arrayB)

    # Calculo de Desviación Estándar
    xDev = math.sqrt(sum(math.pow(i - muA, 2) for i in arrayA) / len(arrayA))
    yDev = math.sqrt(sum(math.pow(i - muB, 2) for i in arrayB) / len(arrayB))

    covarianza = (sum(((arrayA[i] - muA) * (arrayB[i] - muB)) for i in range(0, len(arrayA), 1))) / len(arrayA)
    
    print ('{:.3f}'.format(covarianza / (yDev * xDev)))

In [107]:
ejercicio4(np.array([1, 2, 3, 4, 5]), np.array([5, 4, 3, 2, 1]))

-1.000
